# Generated by Django 4.2 on 2023-07-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseplan',
            name='user',
        ),
    ]
